# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addSpeaker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addSpeaker(object):
    def setupUi(self, addSpeaker):
        addSpeaker.setObjectName("addSpeaker")
        addSpeaker.resize(800, 250)
        self.centralwidget = QtWidgets.QWidget(addSpeaker)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QTextEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(280, 90, 251, 31))
        self.name.setObjectName("name")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(280, 140, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        addSpeaker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(addSpeaker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        addSpeaker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(addSpeaker)
        self.statusbar.setObjectName("statusbar")
        addSpeaker.setStatusBar(self.statusbar)

        self.retranslateUi(addSpeaker)
        QtCore.QMetaObject.connectSlotsByName(addSpeaker)

    def retranslateUi(self, addSpeaker):
        _translate = QtCore.QCoreApplication.translate
        addSpeaker.setWindowTitle(_translate("addSpeaker", "MainWindow"))
        self.label_2.setText(_translate("addSpeaker", "Enter the name of the speaker you want to add to the DB:"))
        self.submit.setText(_translate("addSpeaker", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addSpeaker = QtWidgets.QMainWindow()
    ui = Ui_addSpeaker()
    ui.setupUi(addSpeaker)
    addSpeaker.show()
    sys.exit(app.exec_())
