# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administrator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adminWindow(object):
    def setupUi(self, adminWindow):
        adminWindow.setObjectName("adminWindow")
        adminWindow.resize(800, 422)
        self.centralwidget = QtWidgets.QWidget(adminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 40, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 110, 771, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.addRec = QtWidgets.QPushButton(self.centralwidget)
        self.addRec.setGeometry(QtCore.QRect(240, 250, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addRec.setFont(font)
        self.addRec.setObjectName("addRec")
        self.addSpeaker = QtWidgets.QPushButton(self.centralwidget)
        self.addSpeaker.setGeometry(QtCore.QRect(240, 200, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addSpeaker.setFont(font)
        self.addSpeaker.setObjectName("addSpeaker")
        self.verifySpeaker = QtWidgets.QPushButton(self.centralwidget)
        self.verifySpeaker.setGeometry(QtCore.QRect(240, 300, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verifySpeaker.setFont(font)
        self.verifySpeaker.setObjectName("verifySpeaker")
        adminWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(adminWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        adminWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(adminWindow)
        self.statusbar.setObjectName("statusbar")
        adminWindow.setStatusBar(self.statusbar)

        self.retranslateUi(adminWindow)
        QtCore.QMetaObject.connectSlotsByName(adminWindow)

    def retranslateUi(self, adminWindow):
        _translate = QtCore.QCoreApplication.translate
        adminWindow.setWindowTitle(_translate("adminWindow", "MainWindow"))
        self.label.setText(_translate("adminWindow", "Welcome Back!"))
        self.label_2.setText(_translate("adminWindow", "You may choose one of the following options:"))
        self.addRec.setText(_translate("adminWindow", "Add Record To Speaker"))
        self.addSpeaker.setText(_translate("adminWindow", "Add Speaker"))
        self.verifySpeaker.setText(_translate("adminWindow", "Verify Speaker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminWindow = QtWidgets.QMainWindow()
    ui = Ui_adminWindow()
    ui.setupUi(adminWindow)
    adminWindow.show()
    sys.exit(app.exec_())
