# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'already_enrolled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_already_enrolled(object):
    def setupUi(self, already_enrolled):
        already_enrolled.setObjectName("already_enrolled")
        already_enrolled.resize(596, 288)
        self.centralwidget = QtWidgets.QWidget(already_enrolled)
        self.centralwidget.setObjectName("centralwidget")
        self.line2 = QtWidgets.QLabel(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(60, 80, 591, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line2.setFont(font)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QLabel(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(60, 50, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line1.setFont(font)
        self.line1.setObjectName("line1")
        self.line3 = QtWidgets.QLabel(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(60, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line3.setFont(font)
        self.line3.setObjectName("line3")
        self.backToMenu = QtWidgets.QPushButton(self.centralwidget)
        self.backToMenu.setGeometry(QtCore.QRect(230, 170, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.backToMenu.setFont(font)
        self.backToMenu.setObjectName("backToMenu")
        already_enrolled.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(already_enrolled)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 21))
        self.menubar.setObjectName("menubar")
        already_enrolled.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(already_enrolled)
        self.statusbar.setObjectName("statusbar")
        already_enrolled.setStatusBar(self.statusbar)

        self.retranslateUi(already_enrolled)
        QtCore.QMetaObject.connectSlotsByName(already_enrolled)

    def retranslateUi(self, already_enrolled):
        _translate = QtCore.QCoreApplication.translate
        already_enrolled.setWindowTitle(_translate("already_enrolled", "MainWindow"))
        self.line2.setText(_translate("already_enrolled", "You may go back to menu and verify your identity "))
        self.line1.setText(_translate("already_enrolled", "You have already enrolled yourself in the system."))
        self.line3.setText(_translate("already_enrolled", "through \'Verify\'."))
        self.backToMenu.setText(_translate("already_enrolled", "Back To Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    already_enrolled = QtWidgets.QMainWindow()
    ui = Ui_already_enrolled()
    ui.setupUi(already_enrolled)
    already_enrolled.show()
    sys.exit(app.exec_())
