# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alreadyVerified.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alreadyVerified(object):
    def setupUi(self, alreadyVerified):
        alreadyVerified.setObjectName("alreadyVerified")
        alreadyVerified.resize(800, 240)
        self.centralwidget = QtWidgets.QWidget(alreadyVerified)
        self.centralwidget.setObjectName("centralwidget")
        self.msg = QtWidgets.QLabel(self.centralwidget)
        self.msg.setGeometry(QtCore.QRect(110, 50, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.msg.setFont(font)
        self.msg.setObjectName("msg")
        self.backToMenu = QtWidgets.QPushButton(self.centralwidget)
        self.backToMenu.setGeometry(QtCore.QRect(330, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backToMenu.setFont(font)
        self.backToMenu.setObjectName("backToMenu")
        alreadyVerified.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(alreadyVerified)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        alreadyVerified.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(alreadyVerified)
        self.statusbar.setObjectName("statusbar")
        alreadyVerified.setStatusBar(self.statusbar)

        self.retranslateUi(alreadyVerified)
        QtCore.QMetaObject.connectSlotsByName(alreadyVerified)

    def retranslateUi(self, alreadyVerified):
        _translate = QtCore.QCoreApplication.translate
        alreadyVerified.setWindowTitle(_translate("alreadyVerified", "MainWindow"))
        self.msg.setText(_translate("alreadyVerified", "You have already verified yourself in the system! Good job!"))
        self.backToMenu.setText(_translate("alreadyVerified", "Back To Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alreadyVerified = QtWidgets.QMainWindow()
    ui = Ui_alreadyVerified()
    ui.setupUi(alreadyVerified)
    alreadyVerified.show()
    sys.exit(app.exec_())
