# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'didntEnroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_didntEnroll(object):
    def setupUi(self, didntEnroll):
        didntEnroll.setObjectName("didntEnroll")
        didntEnroll.resize(534, 208)
        self.centralwidget = QtWidgets.QWidget(didntEnroll)
        self.centralwidget.setObjectName("centralwidget")
        self.line2 = QtWidgets.QLabel(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(60, 60, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.line2.setFont(font)
        self.line2.setObjectName("line2")
        self.line1 = QtWidgets.QLabel(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(60, 30, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.line1.setFont(font)
        self.line1.setObjectName("line1")
        self.backToMenu = QtWidgets.QPushButton(self.centralwidget)
        self.backToMenu.setGeometry(QtCore.QRect(210, 110, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.backToMenu.setFont(font)
        self.backToMenu.setObjectName("backToMenu")
        didntEnroll.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(didntEnroll)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 21))
        self.menubar.setObjectName("menubar")
        didntEnroll.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(didntEnroll)
        self.statusbar.setObjectName("statusbar")
        didntEnroll.setStatusBar(self.statusbar)

        self.retranslateUi(didntEnroll)
        QtCore.QMetaObject.connectSlotsByName(didntEnroll)

    def retranslateUi(self, didntEnroll):
        _translate = QtCore.QCoreApplication.translate
        didntEnroll.setWindowTitle(_translate("didntEnroll", "MainWindow"))
        self.line2.setText(_translate("didntEnroll", "You may go back to menu and choose \'Enroll\'."))
        self.line1.setText(_translate("didntEnroll", "You did not enroll yourself in the system."))
        self.backToMenu.setText(_translate("didntEnroll", "Back To Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    didntEnroll = QtWidgets.QMainWindow()
    ui = Ui_didntEnroll()
    ui.setupUi(didntEnroll)
    didntEnroll.show()
    sys.exit(app.exec_())
