# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enrollSuccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_enrollSuccess(object):
    def setupUi(self, enrollSuccess):
        enrollSuccess.setObjectName("enrollSuccess")
        enrollSuccess.resize(800, 155)
        self.centralwidget = QtWidgets.QWidget(enrollSuccess)
        self.centralwidget.setObjectName("centralwidget")
        self.enrll_succ_msg = QtWidgets.QLabel(self.centralwidget)
        self.enrll_succ_msg.setGeometry(QtCore.QRect(220, 30, 401, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.enrll_succ_msg.setFont(font)
        self.enrll_succ_msg.setObjectName("enrll_succ_msg")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 70, 111, 31))
        self.pushButton.setObjectName("pushButton")
        enrollSuccess.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(enrollSuccess)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        enrollSuccess.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(enrollSuccess)
        self.statusbar.setObjectName("statusbar")
        enrollSuccess.setStatusBar(self.statusbar)

        self.retranslateUi(enrollSuccess)
        QtCore.QMetaObject.connectSlotsByName(enrollSuccess)

    def retranslateUi(self, enrollSuccess):
        _translate = QtCore.QCoreApplication.translate
        enrollSuccess.setWindowTitle(_translate("enrollSuccess", "MainWindow"))
        self.enrll_succ_msg.setText(_translate("enrollSuccess", "You have enrolled yourself successfully!"))
        self.pushButton.setText(_translate("enrollSuccess", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    enrollSuccess = QtWidgets.QMainWindow()
    ui = Ui_enrollSuccess()
    ui.setupUi(enrollSuccess)
    enrollSuccess.show()
    sys.exit(app.exec_())
