# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'id_enroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_id_enroll(object):
    def setupUi(self, id_enroll):
        id_enroll.setObjectName("id_enroll")
        id_enroll.resize(525, 188)
        self.centralwidget = QtWidgets.QWidget(id_enroll)
        self.centralwidget.setObjectName("centralwidget")
        self.pleaseEnterID = QtWidgets.QLabel(self.centralwidget)
        self.pleaseEnterID.setGeometry(QtCore.QRect(170, 30, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pleaseEnterID.setFont(font)
        self.pleaseEnterID.setObjectName("pleaseEnterID")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(210, 70, 111, 20))
        self.textEdit.setObjectName("id_box")
        self.submitID = QtWidgets.QPushButton(self.centralwidget)
        self.submitID.setGeometry(QtCore.QRect(230, 110, 71, 23))
        self.submitID.setObjectName("submitID")
        id_enroll.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(id_enroll)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 525, 21))
        self.menubar.setObjectName("menubar")
        id_enroll.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(id_enroll)
        self.statusbar.setObjectName("statusbar")
        id_enroll.setStatusBar(self.statusbar)

        self.retranslateUi(id_enroll)
        QtCore.QMetaObject.connectSlotsByName(id_enroll)

    def retranslateUi(self, id_enroll):
        _translate = QtCore.QCoreApplication.translate
        id_enroll.setWindowTitle(_translate("id_enroll", "MainWindow"))
        self.pleaseEnterID.setText(_translate("id_enroll", "Please enter your ID number:"))
        self.textEdit.setHtml(_translate("id_enroll", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.submitID.setText(_translate("id_enroll", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    id_enroll = QtWidgets.QMainWindow()
    ui = Ui_id_enroll()
    ui.setupUi(id_enroll)
    id_enroll.show()
    sys.exit(app.exec_())
