# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'id_verify.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_id_verify(object):
    def setupUi(self, id_verify):
        id_verify.setObjectName("id_verify")
        id_verify.resize(634, 179)
        self.centralwidget = QtWidgets.QWidget(id_verify)
        self.centralwidget.setObjectName("centralwidget")
        self.pleaseEnterID = QtWidgets.QLabel(self.centralwidget)
        self.pleaseEnterID.setGeometry(QtCore.QRect(220, 40, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pleaseEnterID.setFont(font)
        self.pleaseEnterID.setObjectName("pleaseEnterID")
        self.id_text = QtWidgets.QTextEdit(self.centralwidget)
        self.id_text.setGeometry(QtCore.QRect(250, 70, 131, 20))
        self.id_text.setObjectName("id_text")
        self.submitID = QtWidgets.QPushButton(self.centralwidget)
        self.submitID.setGeometry(QtCore.QRect(274, 100, 91, 23))
        self.submitID.setObjectName("submitID")
        id_verify.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(id_verify)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 21))
        self.menubar.setObjectName("menubar")
        id_verify.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(id_verify)
        self.statusbar.setObjectName("statusbar")
        id_verify.setStatusBar(self.statusbar)

        self.retranslateUi(id_verify)
        QtCore.QMetaObject.connectSlotsByName(id_verify)

    def retranslateUi(self, id_verify):
        _translate = QtCore.QCoreApplication.translate
        id_verify.setWindowTitle(_translate("id_verify", "MainWindow"))
        self.pleaseEnterID.setText(_translate("id_verify", "Please enter your ID number:"))
        self.id_text.setHtml(_translate("id_verify", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.submitID.setText(_translate("id_verify", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    id_verify = QtWidgets.QMainWindow()
    ui = Ui_id_verify()
    ui.setupUi(id_verify)
    id_verify.show()
    sys.exit(app.exec_())
