# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordingSelector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recordingSelector(object):
    def setupUi(self, recordingSelector):
        recordingSelector.setObjectName("recordingSelector")
        recordingSelector.resize(800, 284)
        self.centralwidget = QtWidgets.QWidget(recordingSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.chosen_path = QtWidgets.QTextEdit(self.centralwidget)
        self.chosen_path.setGeometry(QtCore.QRect(340, 200, 161, 31))
        self.chosen_path.setObjectName("chosen_path")
        self.uploadRec = QtWidgets.QPushButton(self.centralwidget)
        self.uploadRec.setGeometry(QtCore.QRect(340, 140, 161, 41))
        self.uploadRec.setObjectName("uploadRec")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 571, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(340, 90, 161, 41))
        self.submit.setObjectName("submit")
        recordingSelector.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(recordingSelector)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        recordingSelector.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(recordingSelector)
        self.statusbar.setObjectName("statusbar")
        recordingSelector.setStatusBar(self.statusbar)

        self.retranslateUi(recordingSelector)
        QtCore.QMetaObject.connectSlotsByName(recordingSelector)

    def retranslateUi(self, recordingSelector):
        _translate = QtCore.QCoreApplication.translate
        recordingSelector.setWindowTitle(_translate("recordingSelector", "MainWindow"))
        self.uploadRec.setText(_translate("recordingSelector", "Upload Recording"))
        self.label.setText(_translate("recordingSelector", "Please select a recording where you would like to check if the speaker appears:"))
        self.submit.setText(_translate("recordingSelector", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recordingSelector = QtWidgets.QMainWindow()
    ui = Ui_recordingSelector()
    ui.setupUi(recordingSelector)
    recordingSelector.show()
    sys.exit(app.exec_())
