# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordingSelector2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recordingSelector2(object):
    def setupUi(self, recordingSelector2):
        recordingSelector2.setObjectName("recordingSelector2")
        recordingSelector2.resize(800, 312)
        self.centralwidget = QtWidgets.QWidget(recordingSelector2)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 671, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(320, 100, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.uploadRec = QtWidgets.QPushButton(self.centralwidget)
        self.uploadRec.setGeometry(QtCore.QRect(320, 160, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uploadRec.setFont(font)
        self.uploadRec.setObjectName("uploadRec")
        self.chosen_path = QtWidgets.QTextEdit(self.centralwidget)
        self.chosen_path.setGeometry(QtCore.QRect(320, 220, 161, 31))
        self.chosen_path.setObjectName("chosen_path")
        recordingSelector2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(recordingSelector2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        recordingSelector2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(recordingSelector2)
        self.statusbar.setObjectName("statusbar")
        recordingSelector2.setStatusBar(self.statusbar)

        self.retranslateUi(recordingSelector2)
        QtCore.QMetaObject.connectSlotsByName(recordingSelector2)

    def retranslateUi(self, recordingSelector2):
        _translate = QtCore.QCoreApplication.translate
        recordingSelector2.setWindowTitle(_translate("recordingSelector2", "MainWindow"))
        self.label.setText(_translate("recordingSelector2", "Please select a speaker recording that you want to add to the database:"))
        self.submit.setText(_translate("recordingSelector2", "Submit"))
        self.uploadRec.setText(_translate("recordingSelector2", "Upload Recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    recordingSelector2 = QtWidgets.QMainWindow()
    ui = Ui_recordingSelector2()
    ui.setupUi(recordingSelector2)
    recordingSelector2.show()
    sys.exit(app.exec_())
