# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verification.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verificationWin(object):
    def setupUi(self, verificationWin):
        verificationWin.setObjectName("verificationWin")
        verificationWin.resize(800, 395)
        self.centralwidget = QtWidgets.QWidget(verificationWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verification = QtWidgets.QLabel(self.centralwidget)
        self.verification.setGeometry(QtCore.QRect(310, 60, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Hadassah Friedlaender")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.verification.setFont(font)
        self.verification.setObjectName("verification")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(280, 160, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.uploadRec = QtWidgets.QPushButton(self.centralwidget)
        self.uploadRec.setGeometry(QtCore.QRect(280, 230, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.uploadRec.setFont(font)
        self.uploadRec.setObjectName("uploadRec")
        self.chosen_path = QtWidgets.QTextEdit(self.centralwidget)
        self.chosen_path.setGeometry(QtCore.QRect(280, 300, 221, 31))
        self.chosen_path.setObjectName("chosen_path")
        verificationWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(verificationWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        verificationWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(verificationWin)
        self.statusbar.setObjectName("statusbar")
        verificationWin.setStatusBar(self.statusbar)

        self.retranslateUi(verificationWin)
        QtCore.QMetaObject.connectSlotsByName(verificationWin)

    def retranslateUi(self, verificationWin):
        _translate = QtCore.QCoreApplication.translate
        verificationWin.setWindowTitle(_translate("verificationWin", "MainWindow"))
        self.verification.setText(_translate("verificationWin", "Verification"))
        self.submit.setText(_translate("verificationWin", "Submit"))
        self.uploadRec.setText(_translate("verificationWin", "Upload Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verificationWin = QtWidgets.QMainWindow()
    ui = Ui_verificationWin()
    ui.setupUi(verificationWin)
    verificationWin.show()
    sys.exit(app.exec_())
