# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificationSuccess.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verificationSuccess(object):
    def setupUi(self, verificationSuccess):
        verificationSuccess.setObjectName("verificationSuccess")
        verificationSuccess.resize(864, 202)
        self.centralwidget = QtWidgets.QWidget(verificationSuccess)
        self.centralwidget.setObjectName("centralwidget")
        self.verify_succ_msg = QtWidgets.QLabel(self.centralwidget)
        self.verify_succ_msg.setGeometry(QtCore.QRect(210, 30, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.verify_succ_msg.setFont(font)
        self.verify_succ_msg.setObjectName("verify_succ_msg")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 90, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        verificationSuccess.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(verificationSuccess)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 864, 21))
        self.menubar.setObjectName("menubar")
        verificationSuccess.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(verificationSuccess)
        self.statusbar.setObjectName("statusbar")
        verificationSuccess.setStatusBar(self.statusbar)

        self.retranslateUi(verificationSuccess)
        QtCore.QMetaObject.connectSlotsByName(verificationSuccess)

    def retranslateUi(self, verificationSuccess):
        _translate = QtCore.QCoreApplication.translate
        verificationSuccess.setWindowTitle(_translate("verificationSuccess", "MainWindow"))
        self.verify_succ_msg.setText(_translate("verificationSuccess", "You have enrolled yourself successfully!"))
        self.pushButton.setText(_translate("verificationSuccess", "Back To Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verificationSuccess = QtWidgets.QMainWindow()
    ui = Ui_verificationSuccess()
    ui.setupUi(verificationSuccess)
    verificationSuccess.show()
    sys.exit(app.exec_())
