# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificationFailed.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_verificationFailed(object):
    def setupUi(self, verificationFailed):
        verificationFailed.setObjectName("verificationFailed")
        verificationFailed.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(verificationFailed)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 360, 131, 51))
        self.pushButton.setStyleSheet("background-color: transparent;\n"
"background-image: url(:kisspng-check-mark-computer-icons-clip-art-5afb299cce0805.0064403315264096288439.qrc);\n"
"background:white;\n"
"border: white;\n"
"background-repeat: none;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 100, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 310, 171, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 200, 671, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 370, 171, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        verificationFailed.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(verificationFailed)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        verificationFailed.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(verificationFailed)
        self.statusbar.setObjectName("statusbar")
        verificationFailed.setStatusBar(self.statusbar)

        self.retranslateUi(verificationFailed)
        QtCore.QMetaObject.connectSlotsByName(verificationFailed)

    def retranslateUi(self, verificationFailed):
        _translate = QtCore.QCoreApplication.translate
        verificationFailed.setWindowTitle(_translate("verificationFailed", "MainWindow"))
        self.pushButton.setText(_translate("verificationFailed", "PushButton"))
        self.label.setText(_translate("verificationFailed", "Verification Failed!"))
        self.pushButton_2.setText(_translate("verificationFailed", "Try Again"))
        self.label_2.setText(_translate("verificationFailed", "The identity does not match the identity provided during the enrollment."))
        self.pushButton_4.setText(_translate("verificationFailed", "Back To Menu"))
#import kisspng-check-mark-computer-icons-clip-art-5afb299cce0805.0064403315264096288439_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verificationFailed = QtWidgets.QMainWindow()
    ui = Ui_verificationFailed()
    ui.setupUi(verificationFailed)
    verificationFailed.show()
    sys.exit(app.exec_())
